[package]
name = "seacc"
version = "0.1.0"
edition = "2024"
authors = ["Cayden Lund <caydenlund@gmail.com>"]
description = "A sea-of-nodes C compiler, written in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/caydenlund/seacc.git"
readme = "README.md"
keywords = ["compiler", "ir", "sea-of-nodes", "optimization"]
categories = ["compilers", "development-tools::build-utils"]

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
